version: 2
formats: []

build:
    image: latest

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false


python:
    version: 3.9.5
    install:
        - requirements: dev-requirements.txt
        - method: pip
          path: .