name: docs

on:
    push:
        branches: [ main ]  

permissions:
    contents: write

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - run: |
                sudo git config --system --add safe.directory "*"

            - name: Setup python
              uses: actions/setup-python@v3

            - name: Install dependencies
              run: |
                python -m pip install sphinx -U 
                python -m pip install sphinx_rtd_theme
                python -m pip install sphinx_autoapi

            - name: Build Docs
              run: |
                make -C docs clean
                make -C docs html
            
            - name: Generate Docs
              run: |
                cd docs/build/html
                git init

                touch .nojekyll

                git add -A

                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"

                git commit -m 'deploy'
    
            - name: Deploy Docs
              uses: ad-m/github-push-action@v0.5.0
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: gh-pages
                directory: ./docs/build/html
